config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :address
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :locations, :dependent => :destroy
  accepts_nested_attributes_for :locations

  # validates :dob,  presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },  presence: true
  validates :age, numericality: true,  presence: true
  validates :first_name, :last_name, length: { maximum: 30 },  presence: true

  validates :mobile,:presence => true,
  :numericality => true,
  :length => { :minimum => 10, :maximum => 15 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json

  respond_to :html, :json

  def index
    @locations = Location.order("id desc").page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
    def create
      @location = Location.create(location_params)
      respond_modal_with @location, location: locations_path
    end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end

  private
  def location_params
    params.require(:location).permit(:address, :location_name, :phone_number, :district, :city, :postcode, :country, :lat, :long)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json, :js

  def index
    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end

  def new
    @user = User.new
    @user.locations.new
    respond_modal_with @user
    # this is needed to seed the form with inputs for source
  end

  def show
  end

  def edit
    respond_modal_with @user
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_modal_with @user, location: users_path
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.js do
          render file: '/users/update.js.erb'
        end


        # respond_modal_with @user, location: users_path
      else
        # respond_modal_with @user, location: users_path
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name,
                                   :email, :mobile, :age, :dob,
                                   locations_attributes: [ :address, :location_name, :phone_number,
                                                           :district, :city, :postcode, :country, :lat, :lng]
                                   )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container justify-content-between">
    <%= link_to 'User Demo', root_path, class: 'navbar-brand' %>

    <%= link_to 'Add User', new_user_path, class: 'btn btn-outline-success my-2 my-sm-0', data: { modal: true } %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class=container>
      <%= yield %>
    </div>
    <div id='modal-holder'></div>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/locations/_form.html.erb
<%= user.fields_for :locations do |location| %>

  <%= location.hidden_field :address %>
  <%= location.hidden_field  :location_name %>
  <%= location.hidden_field  :phone_number %>
  <%= location.hidden_field  :district %>
  <%= location.hidden_field  :postcode %>
  <%= location.hidden_field  :city %>
  <%= location.hidden_field  :country %>
  <%= location.hidden_field  :lat %>
  <%= location.hidden_field  :lng %>

  <div class="form-group">
    <%= label_tag :search, "Address", class: "string" %>
    <%= text_field_tag :location_search, nil, class: "span12 search-query form-control", type: "search" %>
  </div>

<!--  <div class="modal-footer">-->
    <%#= location.submit "Create User", class: 'btn-success btn' %>
<!--  </div>-->
      <%= render partial: "googlemap" %>

<% end %>


<style>
  .pac-container {
    background-color: #FFF;
    z-index: 20;
    position: fixed;
    display: inline-block;
    float: left;
  }
  .modal{
    z-index: 20;
  }
  .modal-backdrop{
    z-index: 10;
  }​
</style>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class="span11">
  <h3>Listing locations</h3>

  <table class="table table-striped">
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Date</th>
    </tr>

  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location.address, location %></td>
      <td><%= link_to location.city, location %></td>
      <td><%= location.postcode %></td>
      <td><%= location.country %></td>
      <td><%= location.lat %></td>
      <td><%= location.lng %></td>
      <td><%= location.created_at.to_s(:short) %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= link_to 'New Location', new_location_path %>
  <br />

  <div class="pagination">
    <%= paginate @locations %>
  </div>
</div>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<div class="span11">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <p>
    <b>Address:</b>
    <%= @location.address %>
  </p>

  <p>
    <b>City:</b>
    <%= @location.city %>
  </p>

  <p>
    <b>Postcode:</b>
    <%= @location.postcode %>
  </p>

  <p>
    <b>Country:</b>
    <%= @location.country %>
  </p>

  <p>
    <b>Lat:</b>
    <span id="location_lat"><%= @location.lat %></span>
  </p>

  <p>
    <b>Lng:</b>
    <span id="location_lng"><%= @location.lng %></span>
  </p>

  <%= render :partial => "googlemap_show" %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user, remote: request.xhr?, html: { data: { modal: true } }) do |user| %>
  <div class="modal-body">

    <div class="row">

      <div class="col-md-6" >
      <%= user.input :first_name %>
      <%= user.input :email %>
      <%= user.input :mobile %>
        <%= render partial: "locations/form" , locals: { user: user } %>
      </div>

      <div class="col-md-6">
        <%= user.input :last_name %>
        <%= user.input :age %>
        <div class="form-group">
          <%= user.label  'Date of Birth' %>
          <%= user.text_field :dob, data:{ provide:'datepicker' }, :id => "datepicker", :class => "form-control" %>
        </div>

      </div>

    </div>
  </div>

  <div class="modal-footer">
    <%= user.button :submit, class: 'btn-success' %>
  </div>
<% end %>

<script>
    $.fn.datepicker.defaults.format = "yyyy-mm-dd";
    $('.datepicker').datepicker({
        startDate: '-3d'
    });
</script>

app/views/users/_googlemap.html.erb
<div id="googlemap"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">
    setTimeout(function() {

        var defaultZoom = 16;

        // create map and add controls
        var mapOptions = {
            center: new google.maps.LatLng(23.022505, 72.571362),
            zoom: defaultZoom,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            scrollwheel: false,
            scaleControl: false
        };
        var map = new google.maps.Map(document.getElementById('googlemap'),mapOptions);


        var mylat = document.getElementById("user_locations_attributes_0_lat").value;
        var mylng = document.getElementById("user_locations_attributes_0_lng").value;
        if (jQuery.isEmptyObject(mylat)) {
            var mylat = '23.022505';
            var mylng = '72.571362UsersController';
            var defaultZoom = 14;
        };

        // set center point of map to be of the Marker or the Default City
        var centrePoint = new google.maps.LatLng(mylat, mylng);
        map.setCenter(centrePoint);
        map.setZoom(defaultZoom);

        // add a draggable marker
        marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: centrePoint
        });

        var defaultImage = new google.maps.MarkerImage(
            "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
            new google.maps.Size(71, 71),
            new google.maps.Point(0, 0),
            new google.maps.Point(17, 34),
            new google.maps.Size(35, 35));
        marker.setIcon(defaultImage);

        google.maps.event.addListener(marker, 'click', toggleBounce);

        // create Info window for marker
        var infowindow = new google.maps.InfoWindow();

        // Address Autocomplete
        var input = document.getElementById('location_search');
        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        // add a drag listener to the map
        google.maps.event.addListener(marker, "dragend", function() {
            var point = marker.getPosition();
            map.panTo(point);
            document.getElementById("user_locations_attributes_0_lat").value = point.lat();
            document.getElementById("user_locations_attributes_0_lng").value = point.lng();
            infowindow.close();
            marker.setIcon(defaultImage);
        });
        var place;
        var photos;

        // Autocomplete Listener
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            place = autocomplete.getPlace();
            marker.setPosition(place.geometry.location);
            map.panTo(place.geometry.location);
            map.setZoom(16);
            document.getElementById("user_locations_attributes_0_lat").value = place.geometry.location.lat();
            document.getElementById("user_locations_attributes_0_lng").value = place.geometry.location.lng();

            // Sets the proper image on the marker. ie. school/hospital marker
            var image = new google.maps.MarkerImage(
                place.icon,
                new google.maps.Size(71, 71),
                new google.maps.Point(0, 0),
                new google.maps.Point(17, 34),
                new google.maps.Size(35, 35));
            marker.setIcon(image);
            marker.setPosition(place.geometry.location);

            console.log(place.address_components);

            var address = '';
            if (place.address_components) {
                address = [(place.address_components[0] &&
                    place.address_components[0].short_name || ''),
                    (place.address_components[1] &&
                        place.address_components[1].short_name || ''),
                    (place.address_components[2] &&
                        place.address_components[2].short_name || '')
                ].join(' ');
            }

            infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
            infowindow.open(map, marker);

            // Autofill the fields in the form. TODO: improve parsing of the returned JSON data.
            var address = place.address_components;
            var website = place.url;

            if (address[address.length - 1]) {
                var zipcode = address[address.length - 1].long_name;
            };
            if (address[address.length - 2]) {
                var country = address[address.length - 2].long_name;
            };
            if (address[address.length - 3]) {
                var city = address[address.length - 3].long_name;
            };
            if (address[address.length - 4]) {
                var sublocality = address[address.length - 4].long_name;
            };
            if (address[0]) {
                var streetnumber = address[0].long_name;
            };
            if (address[1]) {
                var streetname = address[1].long_name;
            };
            if (place.name) {
                var location_name = place.name;
            }
            var formatted_address = place.formatted_address;
            var formatted_phone_number = place.formatted_phone_number;

            if (zipcode){
                document.getElementById("user_locations_attributes_0_postcode").value = zipcode;
            }
            if (city) {
                document.getElementById("user_locations_attributes_0_city").value = city;
            }
            if (country) {
                document.getElementById("user_locations_attributes_0_country").value = country;
            }
            if (sublocality) {
                document.getElementById("user_locations_attributes_0_district").value = sublocality;
            }
            if (streetname) {
                document.getElementById("user_locations_attributes_0_address").value = streetname;
            }
            if (location_name) {
                document.getElementById("user_locations_attributes_0_location_name").value = location_name;
            }
            if (formatted_phone_number) {
                document.getElementById("user_locations_attributes_0_phone_number").value = formatted_phone_number;
            }
            // photos = place.photos;
            // $('#place_images').empty();
            // for (var i = 0; i < photos.length; i++) {
            //     var url = photos[i].getUrl({maxHeight: "1280", maxWidth: "1280"});
            //     $('#place_images').prepend('<img src="' + url + '"/>');
            // }
        });

        // This is the function to animate the marker after dropping it.
        function toggleBounce() {
            if (marker.getAnimation() != null) {
                marker.setAnimation(null);
            } else {
                marker.setAnimation(google.maps.Animation.BOUNCE);
            }
        };

    }, 500)
</script>

app/views/users/_googlemap_show.html.erb
<div id="map" style="width: 100%; height: 360px"></div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<script type="text/javascript">
<!--
  var defaultZoom = 12; // Why zoomed in? Because it looks good.

  var lat = <%= @user.locations.first.lat %>;
  var lng = <%= @user.locations.first.lng %>;

  // create map and add controls
  var mapOptions = {
    center: new google.maps.LatLng(lat, lng),
    zoom: defaultZoom,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    scrollwheel: false,
    scaleControl: false
  };
  var map = new google.maps.Map(document.getElementById('map'),mapOptions);

  var mylat = <%= @user.locations.first.lat %>;
  var mylng = <%= @user.locations.first.lat %>;
  if (jQuery.isEmptyObject(mylat)) {
    var mylat = lat;
    var mylng = lng;
  };

  // set center point of map to be of the Marker or the Default City
  var centrePoint = new google.maps.LatLng(mylat, mylng);

  map.setCenter(centrePoint);
  map.setZoom(defaultZoom);

  // add a draggable marker
  marker = new google.maps.Marker({
    map:map,
    draggable: false,
    animation: google.maps.Animation.DROP,
    position: centrePoint
  });

  // Set marker image
  var defaultImage = new google.maps.MarkerImage(
      "http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
      new google.maps.Size(71, 71),
      new google.maps.Point(0, 0),
      new google.maps.Point(17, 34),
      new google.maps.Size(35, 35)
  );
  marker.setIcon(defaultImage);

//-->
</script>

<br />

app/views/users/_user.html.erb
<table id="users" class="table table-hover table-bordered table-striped nowrap" style="width:100%" data-source="<%= users_url(format: "json") %>">
  <thead class="thead-light">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile</th>
    <th>Age</th>
    <th>DOB</th>
    <th>Edit</th>
    <th>Delete</th>

  </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/users/create.js.erb
$(".modal").modal('hide');
location.reload();

app/views/users/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Edit User</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.bootstrap4.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap4.min.js"></script>
<script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<h1>Users</h1>

<%= render "users/user" %>

app/views/users/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New User</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="modal-header">
  <h5 class="modal-title">User</h5>
  <a href="<%= root_url %>">
    <span>
      <i class="fa fa-chevron-circle-left"></i>
      Back to Home
    </span>
  </a>
</div>

<div class="row">
  <div class="col-md-6">
    <% user = @user.locations.first %>
    <div class="modal-body">

      <b>Full Name:</b>
      <%= @user.first_name + ' ' + @user.last_name %>
      </p>

      <p>
        <b>Email:</b>
        <%= @user.email %>
      </p>

      <p>
        <b>Mobile:</b>
        <%= @user.mobile %>
      </p>

      <p>
        <b>Date of Birth:</b>
        <%= @user.dob %>
      </p>

      <p>
        <b>Address:</b>
        <%=  user.location_name + ', ' +  user.address + ', ' + user.district + ', ' +  user.country + '- ' + user.postcode %>
      </p>
    </div>
  </div>

  <div class="col-md-6">
    <%= render :partial => "googlemap_show" %>

  </div>

</div>




<div class="modal-footer">
</div>

app/views/users/update.js.erb
$(".modal").modal('hide');